sections:
  main:
    display: Main
    fields:
      -
        handle: logo
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Logo
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          width: 50
      -
        handle: logo_white
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Logo white'
          type: assets
          icon: assets
          width: 50
          listable: hidden
          instructions_position: above
          visibility: visible
          max_files: 1
      -
        handle: phone
        field:
          input_type: text
          antlers: false
          display: Phone
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: email
        field:
          input_type: text
          antlers: false
          display: E-mail
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
            - email
      -
        handle: facebook
        field:
          input_type: text
          antlers: false
          display: Facebook
          type: text
          icon: text
          width: 50
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: instagram
        field:
          input_type: text
          antlers: false
          display: Instagram
          type: text
          icon: text
          width: 50
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: linkedin
        field:
          input_type: text
          antlers: false
          display: Linkedin
          type: text
          icon: text
          width: 50
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: whatsapp
        field:
          input_type: text
          antlers: false
          display: Whatsapp
          type: text
          icon: text
          width: 50
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: name
        field:
          input_type: text
          antlers: false
          display: Name
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: adres
        field:
          collapse: false
          always_show_set_button: false
          previews: true
          smart_typography: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          inline: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          remove_empty_nodes: false
          display: Adres
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: contact_image
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Contact image'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
